# escape=`
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# multiline commands require a semicolon and a backtick in the end of each line (except for comments)
RUN Get-ChildItem -Path 'C:\inetpub\wwwroot\App_Config' -Filter '*Unicorn*' -Recurse -Directory | Remove-Item -Force -Recurse; `
    Get-ChildItem -Path 'C:\inetpub\wwwroot\App_Config' -Filter '*.config' -Recurse -File | ForEach-Object { `
        $path = $_.FullName; `
        if (([xml](Get-Content $path)).SelectNodes('/configuration/sitecore/unicorn').Count -gt 0) { `
            Remove-Item $path; `
        } `
    }